version: 43
jobs:
- name: Update GitHub
  jobExecutor: server-docker
  steps:
  - type: PullRepository
    name: Pull from GitHub
    remoteUrl: https://github.com/RaphaelSchuhmann/cratis.git
    userName: RaphaelSchuhmann
    passwordSecret: GitHub-PAT
    targetProject: Cratis
    accessTokenSecret: GitHub-PAT
    refs: refs/heads/* refs/tags/*
    withLfs: false
    force: true
    condition: SUCCESSFUL
    optional: false
  - type: PushRepository
    name: Push to GitHub
    remoteUrl: https://github.com/RaphaelSchuhmann/Cratis.git
    userName: RaphaelSchuhmann
    passwordSecret: GitHub-PAT
    force: true
    condition: SUCCESSFUL
    optional: false
  triggers:
  - type: BranchUpdateTrigger
    userMatch: anyone
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 60
