version: 43
jobs:
	- name : "Push to GitHub"
    secrets:
    	- GitHub_PAT
	steps:
    	- name: "Sync to Remote"
        type: "Repository Sync / PUsh to Remote"
        params:
        	remoteUrl: "https://github.com/RaphaelSchuhmann/cratis.git"
            userName: "RaphaelSchuhmann"
            password: "$$vars.GitHub_PAT"
            ref: "refs/heads/*"
            force: true
		when: "When Changes Published"